BEGIN;

CREATE TABLE IF NOT EXISTS app_clients (
    id BIGSERIAL PRIMARY KEY,
    browser_id TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT app_clients_browser_id_not_blank
        CHECK (LENGTH(BTRIM(browser_id)) > 0)
);

ALTER TABLE app_clients
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE app_clients
    ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE TABLE IF NOT EXISTS documents (
    id BIGSERIAL PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES app_clients(id) ON DELETE CASCADE,
    client_document_id TEXT,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    char_count INTEGER NOT NULL DEFAULT 0,
    raw_word_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT documents_title_not_blank CHECK (LENGTH(BTRIM(title)) > 0),
    CONSTRAINT documents_content_not_blank CHECK (LENGTH(BTRIM(content)) > 0)
);

ALTER TABLE documents
    ADD COLUMN IF NOT EXISTS client_document_id TEXT;

ALTER TABLE documents
    ADD COLUMN IF NOT EXISTS char_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE documents
    ADD COLUMN IF NOT EXISTS raw_word_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE documents
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS idx_documents_client_document_id_unique
    ON documents (client_id, client_document_id)
    WHERE client_document_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_documents_client_updated
    ON documents (client_id, updated_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS analysis_settings (
    id BIGSERIAL PRIMARY KEY,
    client_id BIGINT NOT NULL UNIQUE REFERENCES app_clients(id) ON DELETE CASCADE,
    stop_words_mode TEXT NOT NULL DEFAULT 'default',
    custom_stop_words TEXT[] NOT NULL DEFAULT '{}',
    keywords TEXT[] NOT NULL DEFAULT '{}',
    lemmatization BOOLEAN NOT NULL DEFAULT TRUE,
    ngram_sizes INTEGER[] NOT NULL DEFAULT '{2,3}',
    spam_threshold_percent NUMERIC NOT NULL DEFAULT 3,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS analysis_results (
    id BIGSERIAL PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES app_clients(id) ON DELETE CASCADE,
    analysis_type TEXT NOT NULL,
    selected_document_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    params_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    result JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_actual BOOLEAN NOT NULL DEFAULT TRUE,
    invalidation_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (client_id, analysis_type)
);

CREATE TABLE IF NOT EXISTS default_stop_words (
    id BIGSERIAL PRIMARY KEY,
    word TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS water_markers (
    id BIGSERIAL PRIMARY KEY,
    marker TEXT NOT NULL UNIQUE
);

INSERT INTO default_stop_words (word)
SELECT UNNEST(ARRAY[
    'а',
    'без',
    'безо',
    'близ',
    'благо',
    'благодаря',
    'более',
    'больше',
    'будем',
    'будет',
    'будете',
    'будешь',
    'будто',
    'буду',
    'будут',
    'будь',
    'бы',
    'бывало',
    'был',
    'была',
    'были',
    'было',
    'быть',
    'в',
    'вам',
    'вами',
    'вас',
    'ваш',
    'ваша',
    'ваше',
    'ваши',
    'вверх',
    'вдали',
    'вдоль',
    'ведь',
    'везде',
    'весь',
    'вместо',
    'вне',
    'вниз',
    'внизу',
    'во',
    'вокруг',
    'вон',
    'вообще',
    'вопреки',
    'вот',
    'впрочем',
    'все',
    'всегда',
    'всего',
    'всем',
    'всеми',
    'всему',
    'всех',
    'всею',
    'всю',
    'вся',
    'всякий',
    'где',
    'где-то',
    'да',
    'дабы',
    'даже',
    'далее',
    'для',
    'до',
    'довольно',
    'долго',
    'должен',
    'должна',
    'должно',
    'должны',
    'другой',
    'его',
    'едва',
    'ее',
    'ей',
    'ему',
    'если',
    'есть',
    'еще',
    'же',
    'за',
    'зато',
    'зачем',
    'здесь',
    'и',
    'ибо',
    'из',
    'из-за',
    'из-под',
    'или',
    'им',
    'ими',
    'именно',
    'их',
    'к',
    'как',
    'какая',
    'какие',
    'каким',
    'какими',
    'каких',
    'какой',
    'как-то',
    'кем',
    'когда',
    'когда-то',
    'кого',
    'кое',
    'кое-где',
    'кое-как',
    'кое-кто',
    'кое-куда',
    'кое-чей',
    'кой',
    'коль',
    'ко',
    'кому',
    'конечно',
    'которая',
    'которого',
    'которой',
    'котором',
    'которому',
    'которые',
    'который',
    'которым',
    'которыми',
    'которых',
    'кто',
    'куда',
    'куда-то',
    'ли',
    'либо',
    'лишь',
    'лучше',
    'меж',
    'между',
    'менее',
    'меньше',
    'меня',
    'мне',
    'мной',
    'мною',
    'мог',
    'моги',
    'могла',
    'могли',
    'могло',
    'могу',
    'могут',
    'мое',
    'моего',
    'моей',
    'моем',
    'моему',
    'моим',
    'моими',
    'моих',
    'мой',
    'моя',
    'мы',
    'на',
    'над',
    'надо',
    'назад',
    'наиболее',
    'нам',
    'нами',
    'нас',
    'наш',
    'наша',
    'наше',
    'наши',
    'не',
    'него',
    'нее',
    'ней',
    'нельзя',
    'нем',
    'нему',
    'нет',
    'ни',
    'нибудь',
    'ниже',
    'ним',
    'ними',
    'них',
    'ничего',
    'но',
    'ну',
    'о',
    'об',
    'обо',
    'один',
    'одна',
    'однако',
    'одни',
    'одно',
    'около',
    'он',
    'она',
    'они',
    'оно',
    'опять',
    'от',
    'ото',
    'откуда',
    'отсюда',
    'очень',
    'перед',
    'по',
    'под',
    'подо',
    'пока',
    'поскольку',
    'после',
    'потом',
    'потому',
    'почему',
    'почти',
    'пред',
    'преди',
    'прежде',
    'при',
    'про',
    'просто',
    'против',
    'пусть',
    'ради',
    'раз',
    'разве',
    'с',
    'сам',
    'сама',
    'сами',
    'самим',
    'самими',
    'самих',
    'само',
    'самого',
    'самой',
    'самом',
    'самому',
    'саму',
    'свое',
    'своего',
    'своей',
    'своем',
    'своему',
    'свои',
    'своим',
    'своими',
    'своих',
    'свой',
    'своя',
    'себе',
    'себя',
    'сейчас',
    'сей',
    'сквозь',
    'слишком',
    'со',
    'собой',
    'собою',
    'согласно',
    'совсем',
    'так',
    'такая',
    'также',
    'такие',
    'таким',
    'такими',
    'таких',
    'таков',
    'такого',
    'такое',
    'такой',
    'там',
    'твое',
    'твоего',
    'твоей',
    'твоем',
    'твоему',
    'твой',
    'твоя',
    'те',
    'тебе',
    'тебя',
    'тем',
    'теми',
    'тех',
    'то',
    'тобой',
    'тобою',
    'тогда',
    'того',
    'тоже',
    'той',
    'только',
    'том',
    'тому',
    'тот',
    'тою',
    'ту',
    'туда',
    'ты',
    'у',
    'уж',
    'уже',
    'хоть',
    'хотя',
    'чего',
    'чей',
    'чем',
    'через',
    'что',
    'чтоб',
    'чтобы',
    'чья',
    'чье',
    'чьи',
    'чьим',
    'чьих',
    'эта',
    'эти',
    'этим',
    'этими',
    'этих',
    'это',
    'этого',
    'этой',
    'этом',
    'этому',
    'этот',
    'эту',
    'я',
    'a',
    'about',
    'above',
    'after',
    'again',
    'against',
    'all',
    'am',
    'an',
    'and',
    'any',
    'are',
    'as',
    'at',
    'be',
    'because',
    'been',
    'before',
    'being',
    'below',
    'between',
    'both',
    'but',
    'by',
    'can',
    'could',
    'did',
    'do',
    'does',
    'doing',
    'down',
    'during',
    'each',
    'few',
    'for',
    'from',
    'further',
    'had',
    'has',
    'have',
    'having',
    'he',
    'her',
    'here',
    'hers',
    'herself',
    'him',
    'himself',
    'his',
    'how',
    'i',
    'if',
    'in',
    'into',
    'is',
    'it',
    'its',
    'itself',
    'just',
    'me',
    'more',
    'most',
    'my',
    'myself',
    'no',
    'nor',
    'not',
    'now',
    'of',
    'off',
    'on',
    'once',
    'only',
    'or',
    'other',
    'our',
    'ours',
    'ourselves',
    'out',
    'over',
    'own',
    'same',
    'she',
    'should',
    'so',
    'some',
    'such',
    'than',
    'that',
    'the',
    'their',
    'theirs',
    'them',
    'themselves',
    'then',
    'there',
    'these',
    'they',
    'this',
    'those',
    'through',
    'to',
    'too',
    'under',
    'until',
    'up',
    'very',
    'was',
    'we',
    'were',
    'what',
    'when',
    'where',
    'which',
    'while',
    'who',
    'whom',
    'why',
    'will',
    'with',
    'you',
    'your',
    'yours',
    'yourself',
    'yourselves'
]::text[])
ON CONFLICT DO NOTHING;

INSERT INTO water_markers (marker)
SELECT UNNEST(ARRAY[
    'абсолютно',
    'без всякого сомнения',
    'безусловно',
    'буквально',
    'в большинстве случаев',
    'в некоторой степени',
    'в общем',
    'в общем и целом',
    'в определенной степени',
    'в принципе',
    'в результате',
    'в свою очередь',
    'в связи с этим',
    'в то же время',
    'в целом',
    'важно отметить',
    'важно понимать',
    'вероятно',
    'весьма',
    'видимо',
    'возможно',
    'во многом',
    'вообще',
    'во-первых',
    'во-вторых',
    'вроде',
    'вроде бы',
    'всего лишь',
    'выходит',
    'главным образом',
    'говорят',
    'грубо говоря',
    'далеко не всегда',
    'действительно',
    'достаточно',
    'едва ли',
    'если говорить о',
    'если честно',
    'естественно',
    'значит',
    'значительно',
    'и так далее',
    'и тому подобное',
    'иначе говоря',
    'иногда',
    'как известно',
    'как правило',
    'как говорится',
    'как бы',
    'как можно заметить',
    'как ни странно',
    'как оказывается',
    'как следствие',
    'как уже говорилось',
    'кажется',
    'казалось бы',
    'конечно',
    'конечно же',
    'короче говоря',
    'кроме того',
    'лишь',
    'между прочим',
    'может быть',
    'можно сказать',
    'на данный момент',
    'на мой взгляд',
    'на первый взгляд',
    'на практике',
    'на самом деле',
    'на сегодняшний день',
    'наверное',
    'надо сказать',
    'надо отметить',
    'например',
    'несомненно',
    'нельзя не отметить',
    'нельзя не сказать',
    'необходимо отметить',
    'необходимо понимать',
    'немного',
    'нередко',
    'нужно отметить',
    'нужно понимать',
    'однако',
    'оказывается',
    'определенно',
    'определенным образом',
    'особенно',
    'очевидно',
    'очень',
    'по большому счету',
    'по сути',
    'по сути дела',
    'по этой причине',
    'поэтому',
    'пожалуй',
    'получается',
    'практически',
    'предположительно',
    'прежде всего',
    'примерно',
    'примечательно',
    'просто',
    'разумеется',
    'само собой',
    'само собой разумеется',
    'скорее всего',
    'собственно',
    'собственно говоря',
    'совершенно',
    'соответственно',
    'стоит отметить',
    'стоит сказать',
    'существенно',
    'так или иначе',
    'так сказать',
    'также',
    'таким образом',
    'то есть',
    'фактически',
    'честно говоря',
    'что касается'
]::text[])
ON CONFLICT DO NOTHING;

UPDATE documents
SET
    char_count = LENGTH(content),
    raw_word_count = GREATEST(raw_word_count, 0),
    updated_at = COALESCE(updated_at, created_at, NOW());

COMMIT;
